"""Trusted single-threaded Linux bootstrap. Source input goes only to the runner.

The outer worker retains the namespace init pidfd before acknowledging READY.
Init death terminates every namespace member in the kernel, across sessions and
nested namespaces. This is process ownership, not shared-cgroup OOM isolation.
"""
import ctypes
import json
import os
from pathlib import Path
import re
import select
import shutil
import signal
import socket
import subprocess
import sys

CONTROL_BYTES = 512
CLONE_NEWUSER = 0x10000000
CLONE_NEWPID = 0x20000000
PROFILE_RE = re.compile(r"^vct-browser-(\d+)-(\d+)-[0-9a-f]{32}$")
MAX_RECLAIM_PROFILES = 128


def _prctl(option, value):
    libc = ctypes.CDLL(None, use_errno=True)
    if libc.prctl(option, value, 0, 0, 0) != 0:
        raise OSError(ctypes.get_errno(), "prctl")


def _parent_death(parent):
    _prctl(1, signal.SIGKILL)  # PR_SET_PDEATHSIG; set after credential changes.
    if os.getppid() != parent:
        raise OSError("parent exited")


def _unshare():
    libc = ctypes.CDLL(None, use_errno=True)
    if libc.unshare(CLONE_NEWUSER | CLONE_NEWPID) != 0:
        raise OSError(ctypes.get_errno(), "unshare")


def _map_ids(uid, gid):
    Path("/proc/self/uid_map").write_text(f"{uid} {uid} 1\n")
    Path("/proc/self/setgroups").write_text("deny\n")
    Path("/proc/self/gid_map").write_text(f"{gid} {gid} 1\n")


def _drop_capabilities():
    class Header(ctypes.Structure):
        _fields_ = [("version", ctypes.c_uint32), ("pid", ctypes.c_int)]
    class Data(ctypes.Structure):
        _fields_ = [("effective", ctypes.c_uint32), ("permitted", ctypes.c_uint32),
                    ("inheritable", ctypes.c_uint32)]
    libc = ctypes.CDLL(None, use_errno=True)
    if libc.capset(ctypes.byref(Header(0x20080522, 0)), (Data * 2)()) != 0:
        raise OSError(ctypes.get_errno(), "capset")


def _send(control, **message):
    control.send(json.dumps(message).encode("ascii"))


def _runner_command():
    return [sys.executable, "-m", "backend.app.extraction.browser_runner"]


def _cleanup_profile(directory):
    # Directory is generated by the trusted worker, never by source content.
    try:
        shutil.rmtree(directory)
    except FileNotFoundError:
        pass


def _process_start_time(pid):
    try:
        # /proc/<pid>/stat field 22; split after comm because comm may contain spaces.
        tail = Path(f"/proc/{pid}/stat").read_text().rsplit(")", 1)[1].split()
        return int(tail[19])
    except (OSError, ValueError, IndexError):
        return None


def _reclaim_profiles():
    """Delete profiles whose owning worker no longer exists.

    The scan is finite and only accepts names minted by browser.py. A live PID
    must also have the same proc start time, preventing PID reuse from making a
    dead profile look owned by a new worker.
    """
    matched = 0
    with os.scandir("/tmp") as entries:
        for entry in entries:
            match = PROFILE_RE.fullmatch(entry.name)
            if match is None or not entry.is_dir(follow_symlinks=False):
                continue
            matched += 1
            if matched > MAX_RECLAIM_PROFILES:
                return 1
            pid, start = map(int, match.groups())
            if _process_start_time(pid) == start:
                continue
            _cleanup_profile(entry.path)
    return 0


def _init(control, directory, gate):
    # Parent is outside this PID namespace (getppid() == 0). The bootstrap
    # must receive positive arming confirmation before releasing this gate.
    # A buffered release alone cannot prove the parent was alive at arming.
    _prctl(1, signal.SIGKILL)
    gate.settimeout(2)
    gate.send(b"ARMED")
    if gate.recv(CONTROL_BYTES + 1) != b"1":
        return 1
    gate.close()
    if os.getpid() != 1 or os.geteuid() == 0 or os.getegid() == 0:
        return 1
    _drop_capabilities()
    control.settimeout(2)
    _send(control, kind="READY", pid=1, uid=os.geteuid(), gid=os.getegid())
    if control.recv(CONTROL_BYTES + 1) != b"ACK":
        return 1
    # No browser or filesystem setup precedes the retained owner/ACK.
    os.mkdir(directory, mode=0o700)
    runner = subprocess.Popen(_runner_command(), close_fds=True)
    control.setblocking(False)
    while runner.poll() is None:
        readable, _, _ = select.select([control], [], [], .02)
        if readable and control.recv(CONTROL_BYTES + 1) != b"":
            return 1  # No messages are accepted after ACK.
        if readable:
            return 1  # Worker closed its lifetime channel.
    return 0 if runner.returncode == 0 else 1


def bootstrap(control, directory):
    parent = os.getppid()
    uid, gid = os.geteuid(), os.getegid()
    child = None
    gate_parent = gate_child = None
    try:
        if uid == 0 or gid == 0:
            raise OSError("nonroot required")
        _parent_death(parent)
        _unshare()
        _map_ids(uid, gid)
        _parent_death(parent)
        gate_parent, gate_child = socket.socketpair(socket.AF_UNIX, socket.SOCK_SEQPACKET)
        gate_parent.settimeout(2)
        child = os.fork()
        if child == 0:
            gate_parent.close()
            try:
                status = _init(control, directory, gate_child)
            except BaseException:
                status = 1
            os._exit(status)  # PID 1 exit kills all owned descendants.
        gate_child.close()
        gate_child = None
        _drop_capabilities()
        _send(control, kind="OWNER", pid=child)
        if gate_parent.recv(CONTROL_BYTES + 1) != b"ARMED":
            raise OSError("init not armed")
        gate_parent.send(b"1")
        gate_parent.close()
        gate_parent = None
        control.close()
        _, status = os.waitpid(child, 0)
        _cleanup_profile(directory)
        return 0 if os.waitstatus_to_exitcode(status) == 0 else 1
    except BaseException:
        # No source material or exception text on the protocol channel.
        if gate_parent is not None:
            gate_parent.close()
            gate_parent = None
        if child is not None:
            try:
                os.kill(child, signal.SIGKILL)
                os.waitpid(child, 0)
            except OSError:
                pass
        try:
            _send(control, kind="UNAVAILABLE")
        except OSError:
            pass
        return 1
    finally:
        for gate in (gate_parent, gate_child):
            if gate is not None:
                gate.close()
        control.close()


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "--reclaim":
        return _reclaim_profiles()
    if len(sys.argv) == 3 and sys.argv[1] == "--cleanup":
        _cleanup_profile(sys.argv[2])
        return 0
    control = socket.socket(fileno=int(sys.argv[1]))
    return bootstrap(control, sys.argv[2])


if __name__ == "__main__":
    sys.exit(main())
